# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poreikis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Rinkmena', 'verbose_name_plural': 'Rinkmenos'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizacija', 'verbose_name_plural': 'Organizacijos'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projektas', 'verbose_name_plural': 'Projektai'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Užklausa', 'verbose_name_plural': 'Užklausos'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='project_url',
        ),
        migrations.AddField(
            model_name='request',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='El. pašto adresas pasiteiravimui (nurodyti nebūtina)'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='request',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='poreikis.Dataset', verbose_name='Duomenų rinkmenos'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Projekto ar idėjos ir duomenų poreikio aprašymas'),
        ),
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poreikis.Project', verbose_name='Projektas'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Atidaryta'), (2, 'Uždaryta'), (3, 'Šlamštas')], default=1, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Pakeista'),
        ),
    ]
